// Every bundled pet: which species draws it, its default name, the one-line
// description shown in the pet picker, and its colours (see palettes.mjs for
// what each role means). Several pets can share a species: the three birds
// are one sprite in three palettes.

export const PETS = {
  perch: {
    species: 'bird',
    displayName: 'Perch',
    description: 'A round little teal songbird who keeps an eye on your Claude Code sessions.',
    colors: {
      o: '#15383c',
      h: '#72d8c6',
      b: '#3aa39a',
      s: '#28767a',
      d: '#1d5559',
      w: '#fffdf3',
      c: '#f5e5c3',
      q: '#d8bc8e',
      y: '#ffd27a',
      a: '#f39a36',
      r: '#c2612a',
      O: '#5c2a12',
      e: '#18222d',
      p: '#f4958a',
    },
  },
  ember: {
    species: 'bird',
    displayName: 'Ember',
    description: 'A fiery little songbird with a warm glow and a short fuse for failing tests.',
    colors: {
      o: '#3e1512',
      h: '#ffa25e',
      b: '#e6552e',
      s: '#b13526',
      d: '#7e2320',
      w: '#fffbe3',
      c: '#ffe9a6',
      q: '#e9c26b',
      y: '#fff0a0',
      a: '#ffc93c',
      r: '#c98a1e',
      O: '#5a3408',
      e: '#26100f',
      p: '#ffb08a',
    },
  },
  plum: {
    species: 'bird',
    displayName: 'Plum',
    description: 'A calm violet songbird who reads every diff twice before you do.',
    colors: {
      o: '#271541',
      h: '#c8a0f2',
      b: '#9362d1',
      s: '#6a42a3',
      d: '#4b2c7a',
      w: '#fdf9ff',
      c: '#eadcff',
      q: '#bfa6e3',
      y: '#ffd27a',
      a: '#f39a36',
      r: '#c2612a',
      O: '#5c2a12',
      e: '#1e1430',
      p: '#f59ab8',
    },
  },
  fox: {
    species: 'fox',
    displayName: 'Pip',
    description: 'A russet little fox with a white-tipped tail that swishes while your code builds.',
    colors: {
      o: '#3d1a10',
      h: '#f7a255',
      b: '#e2702c',
      s: '#b24e1f',
      d: '#83361a',
      w: '#fffaf2',
      c: '#f1e4d2',
      q: '#d4bfa6',
      k: '#4a2c24',
      e: '#1d1412',
      p: '#f59a86',
    },
  },
  cat: {
    species: 'cat',
    displayName: 'Miso',
    description: 'A charcoal cat with amber eyes who looks very pleased with your finished work.',
    colors: {
      o: '#15161b',
      h: '#7b808e',
      b: '#585c68',
      s: '#42454f',
      d: '#2b2d35',
      w: '#d3d6de',
      c: '#b1b5c0',
      q: '#8f94a0',
      i: '#f4bf45',
      k: '#e892a2',
      e: '#141519',
      p: '#f09aaa',
    },
  },
  axolotl: {
    species: 'axolotl',
    displayName: 'Nori',
    description: 'A pink axolotl with a wide smile whose frills flutter while it waits for you.',
    colors: {
      o: '#6a2440',
      h: '#ffc9dc',
      b: '#f7a0c0',
      s: '#df7ba3',
      d: '#b85a84',
      w: '#fff4f8',
      c: '#ffe0eb',
      q: '#f2b9ce',
      k: '#e24d86',
      j: '#ff8fb8',
      e: '#2b1320',
      p: '#ff6f9c',
    },
  },
  capybara: {
    species: 'capybara',
    displayName: 'Bean',
    description: 'A round, unhurried capybara who balances a tiny orange on its head while it waits.',
    colors: {
      o: '#3a2417',
      h: '#bf8c63',
      b: '#9d6c48',
      s: '#7d5237',
      d: '#5c3b27',
      w: '#d9ad85',
      c: '#c49670',
      q: '#a67b58',
      k: '#6b4430',
      e: '#23160f',
      p: '#e0917e',
      y: '#ffc466',
      a: '#f7962a',
      r: '#d06d18',
      O: '#6b3510',
    },
  },
  robot: {
    species: 'robot',
    displayName: 'Bolt',
    description: 'A little steel robot with a blue visor and an antenna that blinks while it works.',
    colors: {
      o: '#262e3d',
      h: '#f2f5f9',
      b: '#cdd4de',
      s: '#9ba7b7',
      d: '#6d798c',
      k: '#1f3f78',
      j: '#4a7cc9',
      e: '#9ff0ff',
      p: '#f5a3b5',
      y: '#ffd84a',
      O: '#6b4a00',
    },
  },
  ghost: {
    species: 'ghost',
    displayName: 'Wisp',
    description: 'A soft little ghost that floats beside your sessions and fades out when things are quiet.',
    colors: {
      o: '#8676bd',
      c: '#b8acdf',
      h: '#ffffff',
      b: '#f7f5ff',
      s: '#e2dcf5',
      d: '#c7bde6',
      e: '#2e2445',
      p: '#f7a8c4',
    },
  },
};
